spring.application.name=project_02

spring.datasource.url=jdbc:mysql://localhost:3306/project_02?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Tkdfbf1354!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect